repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.5.0
          - flake8-isort==3.0.1
          - pydocstyle==5.0.2
        files: ^(xknx|test)/.+\.py$
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
      - id: no-commit-to-branch
        args:
          - --branch=master
  - repo: https://github.com/prettier/prettier
    rev: 2.0.4
    hooks:
      - id: prettier
        stages: [manual]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.4'
    hooks:
    -   id: autopep8
