name: Pre-commit auto-update

on:
  schedule:
    - cron: "0 8 15 * *"
  # on demand  
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v4
      
      - uses: browniebroke/pre-commit-autoupdate-action@v1.0.0
      
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
