name: GitHub Actions Version Updater

# Controls when the action will run.
on:
  schedule:
    # Automatically run on every Saturday
    - cron:  '0 19 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.WORKFLOW_UPDATER_SECRET }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.7.3
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.WORKFLOW_UPDATER_SECRET }}
